### ISSUE TITLE
Error when exporting

### ISSUE THREAD

**Issue by dloopd** [alessandro-zomparelli/gcode-exporter#2]
Hello, thank you for this addon.
When I attempt to export most solid objects, I'll get this error:

`Traceback (most recent call last):
  File "C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\gcode-exporter-master\gcode_export.py", line 268, in execute
    ordered_verts = find_curves(edges, len(mesh.vertices))
  File "C:\Users\*****\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\gcode-exporter-master\utils.py", line 81, in find_curves
    verts_dict.pop(new_point)
KeyError: None

location: <unknown location>:-1

`

Strangely, the bug only occurs sporadically on some primitives. The default, undeleted cube will export fine. I have gotten it to work with a cylinder as well. I tested on all versions of blender from 2.8., and also tried exporting other objects from a newly opened file and reinstalling gcode exporter.
Is this intended behavior? It's hard to tell with the wiki being gone. If you could offer some guidance (and maybe upload the wiki again) it would be much appreciated.

**Comment by BassT23** [comment]
+1

```
Python: Traceback (most recent call last):
  File "/home/basst/.config/blender/3.6/scripts/addons/gcode-exporter-master/gcode_export.py", line 268, in execute
    ordered_verts = find_curves(edges, len(mesh.vertices))
  File "/home/basst/.config/blender/3.6/scripts/addons/gcode-exporter-master/utils.py", line 81, in find_curves
    verts_dict.pop(new_point)
KeyError: None
```

**Comment by alessandro-zomparelli** [comment]
Hi, can you please provide a screenshot where I can see the geometry that you are trying to export?

**Comment by BassT23** [comment]
Hi,
nice to see, that you will help us :)
I'm new in 3D MOdeling and printing, so forgive me, if the infos not directly what you need. Please descripe more how I can help ;)
![Screenshot_20230701_130647](https://github.com/alessandro-zomparelli/gcode-exporter/assets/30832786/287f7ad0-7ead-4751-9536-26e057be129d)
![Screenshot_20230701_130813](https://github.com/alessandro-zomparelli/gcode-exporter/assets/30832786/0eceb280-f4b9-4d8d-8d63-c9a110762cc7)

I use "Blender" for now (my first try - like I said) :)

**Comment by BassT23** [comment]
I tryed out some more files now, but all with the same problem, ...
Could it be, that I need a pip plugin - curves?
How to install it? - Which package?

**Comment by alessandro-zomparelli** [comment]
Ok, I see the misunderstanding, and it's a common one. My bad for not proving a proper documentation.
Anyway, the aim of the exporter is to export and it's meant to be used with curves or meshes with only edges representing a printing path. What you probably need is a slicing software, that takes as input a 3D solid model.
I use it in combination with Tissue's contour curves or geometry nodes, and mostly for printing outer shells without infill or supports.
